### ISSUE TITLE
Edge Legacy drops CSS rules including :focus-within

### ISSUE THREAD

**Issue by Ariane-B** [matteobad/focus-within-polyfill#61]
In my VM's version of Edge (EdgeHTML 18), using focus-within-polyfill properly adds the "focus-within" attributes to elements.

However, let's say I have a CSS rule like this:

```scss
&:hover, &[focus-within], &:focus-within {
	& > .dropdown-menu { opacity: 1; visibility: visible; }
}
```

Edge will drop the whole thing, and neither the `[focus-within]`, nor the `:hover` part applies.

For this to work, I'll need duplicate rules:

```scss
&:hover, &[focus-within] {
	& > .dropdown-menu { opacity: 1; visibility: visible; }
}

&:focus-within {
	& > .dropdown-menu { opacity: 1; visibility: visible; }
}
```

Of course, none of this is your fault. But I thought it might be useful tell you, so you could put this information in the Readme, since people might be scratching their heads as to why the polyfill "doesn't work" on Edge Legacy (and probably IE).

**Comment by matteobad** [comment]
Hi @Ariane-B,

thank you for your interest. Unfortunately, IE11 and EDGE won't parse the entire CSS block if one or more rules are unknown. This is to be expected. To work around this the duplication is necessary, however, you can use this PostCSS plugin https://github.com/jonathantneal/postcss-focus-within

I should add this do the README.md but don't have a lot of time lately. If you would like to make a small PR with this I would really appreciate it.

Thank you

**Comment by Ariane-B** [comment]
Done. Phew, that took me a long time, since it was my first time fiddling with both Markdown files and pull requests. I hope that's satisfactory. :)
