### ISSUE TITLE
Use of focus-within-polyfill breaks SSR

### ISSUE THREAD

**Issue by nantunes** [matteobad/focus-within-polyfill#73]
**Describe the bug**
Usage of this library with next.js causes a `ReferenceError: document is not defined` in the server.

**Expected behavior**
The code should check the running environment and do nothing when at the server side.

**Comment by nantunes** [comment]
Possible fix: https://github.com/matteobad/focus-within-polyfill/pull/74

**Comment by matteobad** [comment]
Hi @nantunes, thank you for your help, it seems pretty straight forward, I will merge this ASAP ;)
