### ISSUE TITLE
focus-within class should be applied to element with focus

### ISSUE THREAD

**Issue by mcalmus** [matteobad/focus-within-polyfill#80]
**Describe the bug**

When an element has focus the focus-within class is applied to its parent elements. In order to match the `:focus-within` pseudo selector, the focused element should also have the class applied.

https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within

**To Reproduce**
1) Go to focusable-divs demo (https://matteobad.github.io/focus-within-polyfill/demos/focusable-divs.html) in a browser that supports pseudo selector
2) In debugger add a selector:
  .focusable-divs:focus-within {
    background-color: blue;
  }
3) In a browser that doesn't support pseudo selector do the same except add the following:
  .focusable-divs.focus-within {
    background-color: blue;
  }
4) Highlight the "Focusable <div>s" title

**Expected behavior**
Background color of parent div should turn blue.

**Actual behavior**
Background color turns blue in browsers that support pseudo selector but not those that do not.

**Comment by matteobad** [comment]
Hi @mcalmus, thank you for taking the time to make a PR. I will look at it ASAP so that it can be merged 👍
