### ISSUE TITLE
Version 5.2.0 breaks in the browser

### ISSUE THREAD

**Issue by nantunes** [matteobad/focus-within-polyfill#93]
**Describe the bug**
All applications that got the 5.2.0 update broke with error like this:
```
Uncaught ReferenceError: applyFocusVisiblePolyfill is not defined
    at focus-within-polyfill.js:formatted:1
    at Object../node_modules/focus-within-polyfill/dist/focus-within-polyfill.js (focus-within-polyfill.js:formatted:1)
    at __webpack_require__ (focus-within-polyfill.js:formatted:1)
    at fn (focus-within-polyfill.js:formatted:1)
```

**To Reproduce**
1. Upgrade focus-within-polyfill to 5.2.0
2. Build your web app
3. Open it in the browser
4. See error in the console, and probably nothing in the page

**Additional context**
https://github.com/matteobad/focus-within-polyfill/commit/1531ce78d25759409132ad9d96e362938a189ac5
I think references to `applyFocusVisiblePolyfill` were supposed to be named `applyFocusWithinPolyfill`.

**Comment by govcharenko** [comment]
Have the same issue with 5.2.0.

**Comment by kabforks** [comment]
Can confirm. Rolling back to 5.1.0.

**Comment by matteobad** [comment]
Sorry for the inconvenience, I accidentally publish an incomplete version. Deprecating 5.2..0 right while working on 5.3.0. As of right now please roll back to 5.1.0

Apologies 🤦‍♂️
